# Generated by Django 5.0.9 on 2025-07-03 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(max_length=255)),
                ('auth_type', models.CharField(default='phone', max_length=20)),
                ('social_id', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'App_Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App_OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.DecimalField(decimal_places=2, max_digits=18)),
                ('product_name_en', models.CharField(max_length=255)),
                ('product_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_type', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'App_OrderItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(blank=True, max_length=255, null=True)),
                ('co_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('co_name_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Companys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('group_id', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product_image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('product_unit1', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product_unit2', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product_unit3', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product_unit1_2', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product_unit1_3', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unit2_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unit3_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_zero', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('product_buy_number', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product_max_disc', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product_allow_disc', models.BooleanField(default=True)),
                ('product_made', models.CharField(blank=True, max_length=255, null=True)),
                ('product_minus', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_id', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product_id', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('store_id', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Product_Amount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name_ar', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Product_Categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('pd_id', models.AutoField(primary_key=True, serialize=False)),
                ('pd_code', models.CharField(blank=True, max_length=255, null=True)),
                ('pd_name_ar', models.TextField(blank=True, null=True)),
                ('pd_name_en', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
                ('insert_uid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Product_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(blank=True, max_length=255, null=True)),
                ('group_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('group_name_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Product_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Product_Images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unit_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_name_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Product_Unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
