# Generated by Django 5.0.9 on 2025-07-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app_order',
            options={'managed': True},
        ),
    ]
