# Generated by Django 5.0.9 on 2025-07-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_app_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app_order',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='productunit',
            table='product_units',
        ),
    ]
