# Generated by Django 5.0.9 on 2025-07-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_app_order_options_alter_productunit_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'otp',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
