from django.db import models

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)  # Use AutoField for auto-incrementing primary key
    product_code = models.CharField(max_length=255, blank=True, null=True)
    product_fast_code = models.CharField(max_length=255, blank=True, null=True)
    product_int_code = models.CharField(max_length=255, blank=True, null=True)
    product_name_ar = models.CharField(max_length=255, blank=True, null=True)
    product_name_en = models.CharField(max_length=255, blank=True, null=True)
    product_scientific_name = models.CharField(max_length=255, blank=True, null=True)
    product_drug = models.CharField(max_length=255, blank=True, null=True)
    company_id = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_has_expire = models.CharField(max_length=1, blank=True, null=True)
    site_id = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_buy_number = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_big_number = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_small_number = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sell_price = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_disc1 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_disc2 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    tax_price = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    buy_price = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    deleted = models.CharField(max_length=1, blank=True, null=True)
    active = models.CharField(max_length=1, blank=True, null=True)
    product_unit1 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_unit2 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_unit3 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_unit1_2 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_unit1_3 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    group_id = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    pd_id = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_print_barcode = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_allow_disc = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_max_disc = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    insert_date = models.DateTimeField(blank=True, null=True)
    insert_uid = models.CharField(max_length=255, blank=True, null=True)
    up_date = models.DateTimeField(blank=True, null=True)
    up_uid = models.CharField(max_length=255, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    product_minus = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_made = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_int_code1 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code2 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code3 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code4 = models.CharField(max_length=255, blank=True, null=True)
    product_sale_unit = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_unit1_sale = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    unit2_sell_price = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    unit3_sell_price = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sell_clause = models.CharField(max_length=255, blank=True, null=True)
    unit2_sell_price_clause = models.CharField(max_length=255, blank=True, null=True)
    unit3_sell_price_clause = models.CharField(max_length=255, blank=True, null=True)
    amount_zero = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    product_int_code5 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code6 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code7 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code8 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code9 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code10 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code11 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code12 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code13 = models.CharField(max_length=255, blank=True, null=True)
    product_int_code14 = models.CharField(max_length=255, blank=True, null=True)
    no_print_name = models.CharField(max_length=255, blank=True, null=True)
    product_image_url = models.URLField(max_length=300,blank=True, null=True)

    class Meta:
        db_table = 'Products'  # Specify the exact table name

    def __str__(self):
        return self.product_name_en
